# Generated by Django 5.2.10 on 2026-01-15 12:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('exchange', models.CharField(default='KRX', max_length=20)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'symbols',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlcv', to='market.symbol')),
            ],
            options={
                'db_table': 'ohlcv',
                'ordering': ['symbol', 'date'],
                'indexes': [models.Index(fields=['symbol', 'date'], name='ohlcv_symbol__9bcc51_idx'), models.Index(fields=['date'], name='ohlcv_date_c1f745_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('ma5', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ma10', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ma20', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ma60', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ma112', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ma224', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('volume_avg_20', models.BigIntegerField(blank=True, null=True)),
                ('volume_avg_60', models.BigIntegerField(blank=True, null=True)),
                ('week52_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('week52_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('yearly_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('yearly_low_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='market.symbol')),
            ],
            options={
                'db_table': 'indicators',
                'ordering': ['symbol', 'date'],
                'indexes': [models.Index(fields=['symbol', 'date'], name='indicators_symbol__e2de80_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('pattern_type', models.CharField(choices=[('NONE', 'No Pattern'), ('P1', 'Pattern 1'), ('P2', 'Pattern 2')], default='NONE', max_length=10)),
                ('checklist_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='MEDIUM', max_length=10)),
                ('start_signal', models.BooleanField(default=False)),
                ('risk_signal', models.BooleanField(default=False)),
                ('sell_signal', models.BooleanField(default=False)),
                ('checklist_json', models.JSONField(blank=True, default=dict)),
                ('triggers_json', models.JSONField(blank=True, default=dict)),
                ('pattern_evidence_json', models.JSONField(blank=True, default=dict)),
                ('rules_version', models.CharField(blank=True, max_length=64)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='market.symbol')),
            ],
            options={
                'db_table': 'evaluations',
                'ordering': ['-date', '-checklist_score'],
                'indexes': [models.Index(fields=['symbol', 'date'], name='evaluations_symbol__4d7502_idx'), models.Index(fields=['pattern_type', 'checklist_score'], name='evaluations_pattern_493766_idx'), models.Index(fields=['start_signal'], name='evaluations_start_s_d82dfc_idx'), models.Index(fields=['risk_signal'], name='evaluations_risk_si_5d5883_idx'), models.Index(fields=['sell_signal'], name='evaluations_sell_si_a27b73_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
