# Generated by Django 5.2.10 on 2026-01-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='listing_date',
            field=models.DateField(blank=True, help_text='상장일', null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='shares_outstanding',
            field=models.BigIntegerField(blank=True, help_text='상장주식수', null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='pattern_type',
            field=models.CharField(choices=[('NONE', 'No Pattern'), ('P1', 'Pattern 1'), ('P2', 'Pattern 2'), ('P3', 'Pattern 3')], default='NONE', max_length=10),
        ),
    ]
