# Generated by Django 5.2.10 on 2026-01-17 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0003_timeframeanalysis_technicalindicator"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Feature Set명"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "features",
                    models.JSONField(default=list, verbose_name="Feature 목록"),
                ),
                ("start_date", models.DateField(verbose_name="데이터 시작일")),
                ("end_date", models.DateField(verbose_name="데이터 종료일")),
                (
                    "total_samples",
                    models.IntegerField(default=0, verbose_name="총 샘플 수"),
                ),
                (
                    "positive_samples",
                    models.IntegerField(default=0, verbose_name="양성 샘플 수"),
                ),
                (
                    "negative_samples",
                    models.IntegerField(default=0, verbose_name="음성 샘플 수"),
                ),
                (
                    "preprocessing_steps",
                    models.JSONField(default=list, verbose_name="전처리 단계"),
                ),
                (
                    "scaler_params",
                    models.JSONField(default=dict, verbose_name="Scaler 파라미터"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "Feature Set",
                "verbose_name_plural": "Feature Sets",
                "db_table": "feature_sets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="모델명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("CLASSIFIER", "분류 모델 (승률 예측)"),
                            ("REGRESSOR", "회귀 모델 (수익률 예측)"),
                            ("LSTM", "LSTM (시계열 예측)"),
                            ("ENSEMBLE", "앙상블 모델"),
                        ],
                        max_length=20,
                        verbose_name="모델 타입",
                    ),
                ),
                ("algorithm", models.CharField(max_length=50, verbose_name="알고리즘")),
                (
                    "model_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ml_models/",
                        verbose_name="모델 파일",
                    ),
                ),
                ("version", models.CharField(max_length=20, verbose_name="버전")),
                (
                    "accuracy",
                    models.FloatField(blank=True, null=True, verbose_name="정확도"),
                ),
                (
                    "precision",
                    models.FloatField(blank=True, null=True, verbose_name="정밀도"),
                ),
                (
                    "recall",
                    models.FloatField(blank=True, null=True, verbose_name="재현율"),
                ),
                (
                    "f1_score",
                    models.FloatField(blank=True, null=True, verbose_name="F1 Score"),
                ),
                (
                    "auc_score",
                    models.FloatField(blank=True, null=True, verbose_name="AUC Score"),
                ),
                ("mse", models.FloatField(blank=True, null=True, verbose_name="MSE")),
                ("mae", models.FloatField(blank=True, null=True, verbose_name="MAE")),
                ("rmse", models.FloatField(blank=True, null=True, verbose_name="RMSE")),
                (
                    "train_start_date",
                    models.DateField(blank=True, null=True, verbose_name="학습 시작일"),
                ),
                (
                    "train_end_date",
                    models.DateField(blank=True, null=True, verbose_name="학습 종료일"),
                ),
                (
                    "test_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="테스트 시작일"
                    ),
                ),
                (
                    "test_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="테스트 종료일"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRAINING", "학습 중"),
                            ("TRAINED", "학습 완료"),
                            ("EVALUATING", "평가 중"),
                            ("DEPLOYED", "배포 완료"),
                            ("FAILED", "학습 실패"),
                        ],
                        default="TRAINING",
                        max_length=20,
                    ),
                ),
                (
                    "trained_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="학습 완료일"
                    ),
                ),
                (
                    "deployed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="배포일"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "features",
                    models.JSONField(default=list, verbose_name="Feature 목록"),
                ),
                (
                    "hyperparameters",
                    models.JSONField(default=dict, verbose_name="하이퍼파라미터"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="활성화 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "ML 모델",
                "verbose_name_plural": "ML 모델",
                "db_table": "ml_models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="결과일")),
                ("total_return", models.FloatField(verbose_name="총 수익률")),
                ("annualized_return", models.FloatField(verbose_name="연환산 수익률")),
                ("sharpe_ratio", models.FloatField(verbose_name="샤프 비율")),
                ("max_drawdown", models.FloatField(verbose_name="최대 낙폭")),
                ("total_trades", models.IntegerField(verbose_name="총 거래 횟수")),
                ("winning_trades", models.IntegerField(verbose_name="수익 거래")),
                ("losing_trades", models.IntegerField(verbose_name="손실 거래")),
                ("win_rate", models.FloatField(verbose_name="승률")),
                ("avg_win", models.FloatField(verbose_name="평균 수익")),
                ("avg_loss", models.FloatField(verbose_name="평균 손실")),
                ("profit_factor", models.FloatField(verbose_name="Profit Factor")),
                (
                    "direction_accuracy",
                    models.FloatField(verbose_name="방향 예측 정확도"),
                ),
                (
                    "top_decile_return",
                    models.FloatField(verbose_name="상위 10% 수익률"),
                ),
                (
                    "bottom_decile_return",
                    models.FloatField(verbose_name="하위 10% 수익률"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_results",
                        to="ml.mlmodel",
                        verbose_name="모델",
                    ),
                ),
            ],
            options={
                "verbose_name": "ML 백테스트 결과",
                "verbose_name_plural": "ML 백테스트 결과",
                "db_table": "ml_backtest_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MLFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "features",
                    models.JSONField(default=dict, verbose_name="Feature 값들"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "feature_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_features",
                        to="ml.featureset",
                        verbose_name="Feature Set",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_features",
                        to="market.symbol",
                        verbose_name="종목",
                    ),
                ),
            ],
            options={
                "verbose_name": "ML Feature",
                "verbose_name_plural": "ML Features",
                "db_table": "ml_features",
                "ordering": ["-date"],
                "unique_together": {("symbol", "date", "feature_set")},
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_date", models.DateField(verbose_name="예측일")),
                ("target_date", models.DateField(verbose_name="목표일")),
                (
                    "predicted_direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UP", "상승"),
                            ("DOWN", "하락"),
                            ("SIDEWAYS", "횡보"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="예측 방향",
                    ),
                ),
                (
                    "predicted_return",
                    models.FloatField(
                        blank=True, null=True, verbose_name="예측 수익률"
                    ),
                ),
                (
                    "predicted_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="예측가",
                    ),
                ),
                ("confidence", models.FloatField(verbose_name="확신도 (0-1)")),
                (
                    "probability",
                    models.JSONField(default=dict, verbose_name="클래스별 확률"),
                ),
                (
                    "feature_importance",
                    models.JSONField(default=dict, verbose_name="Feature 중요도"),
                ),
                (
                    "actual_return",
                    models.FloatField(
                        blank=True, null=True, verbose_name="실제 수익률"
                    ),
                ),
                (
                    "actual_direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UP", "상승"),
                            ("DOWN", "하락"),
                            ("SIDEWAYS", "횡보"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="실제 방향",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="예측 적중 여부"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="market.evaluation",
                        verbose_name="평가",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="ml.mlmodel",
                        verbose_name="모델",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="market.symbol",
                        verbose_name="종목",
                    ),
                ),
            ],
            options={
                "verbose_name": "예측",
                "verbose_name_plural": "예측",
                "db_table": "predictions",
                "ordering": ["-prediction_date"],
                "unique_together": {("model", "symbol", "prediction_date")},
            },
        ),
    ]
